### ISSUE TITLE
How would you like to be credited for your sample data?

### ISSUE THREAD

**Issue by joeclark-phd** [Tw1ddle/MarkovNameGenerator#2]
Hi, I just borrowed your training data files for a very similar project I've implemented in Java.  I gave you credit in [the project README](https://github.com/joeclark-phd/procedural-generation-examples), just posting an issue here to let you know.  Also, please let me know if you'd like me to give attribution in a different way!

**Comment by Tw1ddle** [comment]
Thanks for the mention, that looks fine to me. Good to see someone finding a use for the sample data, they are mostly based off lists on Wikipedia and census sources I collected up over a few years :smile:
