### ISSUE TITLE
Add Fighting Baseball Roster

### ISSUE THREAD

**Issue by Starmann** [Tw1ddle/MarkovNameGenerator#3]
Your site is amazing. Please add this roster from the 1994 game Fighting Baseball (It generates some amazing results)

[fighting_baseball_full_roster.txt](https://github.com/Tw1ddle/MarkovNameGenerator/files/3913869/fighting_baseball_full_roster.txt)

An example of it in use:

![](https://media.discordapp.net/attachments/551492209065721857/651206855074512919/unknown.png)

**Comment by jaytimbadia** [comment]
> Your site is amazing. Please add this roster from the 1994 game Fighting Baseball (It generates some amazing results)
> 
> [fighting_baseball_full_roster.txt](https://github.com/Tw1ddle/MarkovNameGenerator/files/3913869/fighting_baseball_full_roster.txt)
> 
> An example of it in use:
> 
> ![](https://camo.githubusercontent.com/fff7662f0487859f8d8861881a6208a8a7b881c9c8fb795fc3ed155b1075298f/68747470733a2f2f6d656469612e646973636f72646170702e6e65742f6174746163686d656e74732f3535313439323230393036353732313835372f3635313230363835353037343531323931392f756e6b6e6f776e2e706e67)

@Starmann Can you please share your script for generating names from custom file?

I am new to Haxe and don't know much about it. 
At present, I have just installed namegen library and just ran hello world application.

It would be really helpful if you can share your script and steps on how to print generated words on console or may be in one text file?

Thank you!!

**Comment by Tw1ddle** [comment]
I added your baseball names preset: https://github.com/Tw1ddle/MarkovNameGenerator/commit/e88b55dc1bf26a5a11f4dce0afebc324d6eb3295

I'll update the copy on my site shortly. In the meantime you can hit the "Settings" button on the webpage and type the names you want to use too: https://www.samcodes.co.uk/project/markov-namege - like this:

<img width="1575" alt="2021-11-06_14h46_26" src="https://user-images.githubusercontent.com/1332318/140613715-3bb1cc73-51b9-4994-9cfd-fab17e9eaa67.png">
n/
