### ISSUE TITLE
External API?

### ISSUE THREAD

**Issue by AbrahamBrookes** [Tw1ddle/MarkovNameGenerator#6]
Is there any way to access this name generator from outside the project? I am working in PHP and I would love to be able to use this tool to generate names in that project. I can execute arbitrary console commands from PHP. Is there any way to interact with this tool in order to feed in seed data, set the generator settings, and retrieve a list of generated strings? Or is this repo kind of a standalone thing?

**Comment by Tw1ddle** [comment]
There isn't an external API to use it from non-Haxe code at the minute. I might try making one at some point.

I imagine I'd write an interface for the haxelib in this subfolder, then compile this part to php, which you could then call from php: https://github.com/Tw1ddle/MarkovNameGenerator/tree/master/lib

**Comment by Tw1ddle** [comment]
If you are thinking of doing it, you might prefer to port it to php if you don't know Haxe already, but it's a nice language to learn 😛

**Comment by Tw1ddle** [comment]
I've split the library code out into a separate repo here: https://github.com/Tw1ddle/markov-namegen-lib

You can generate PHP/js/python/whatever versions of the library code by running "haxe build.hxml" from the root of the repo. I've attached the generated PHP for your convenience.

I didn't notice an option to pack the generated output into a single file, so might be a bit unwieldy to use, hope it's some use anyway!

[generated_code.zip](https://github.com/Tw1ddle/MarkovNameGenerator/files/7716520/generated_code.zip)
